// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lcvqxmjoyqujdqcbgjkp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxjdnF4bWpveXF1amRxY2JnamtwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk3ODY2ODUsImV4cCI6MjA4NTM2MjY4NX0.OiQ3EKS0hrFkHCDb0_bZxd_Vzw1sVtU3OlVwsw-DUSw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});